version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bruteforce-ipInsight-poc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1js2rcdnyg2no"
s3_prefix = "bruteforce-ipInsight-poc"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppCode=\"\" VPCName=\"\" EnvironmentType=\"\" BillingAndScalingMode=\"ONDEMAND\""